name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        go: [ 1.24, 1.23 ]
        include:
          - go: 1.24
            lint: true
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v5

      # Running golangci-lint
      - name: Linting
        if: matrix.lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
      # Install Go
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          # apt-get update && apt-get install gcc -y
          go test -parallel 20 -v -race -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash)

  # For github to have a unique status check name
  build-status:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - run: echo 'All good'
